# render.yaml - Clean Configuration for Habu Clean Room MCP Server
databases:
  - name: habu-mcp-db
    databaseName: habu_mcp_db
    user: habu_mcp_user
    plan: free

services:
  # MCP Server
  - type: web
    name: habu-mcp-server-v2
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: JOKE_MCP_SERVER_API_KEY
        sync: false
      - key: HABU_CLIENT_ID
        sync: false
      - key: HABU_CLIENT_SECRET
        sync: false
      - key: HABU_USE_MOCK_DATA
        value: "true"
      - key: PORT
        value: "8000"

  # Demo API
  - type: web
    name: habu-demo-api-v2
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python demo_api.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: JOKE_MCP_SERVER_API_KEY
        sync: false
      - key: HABU_CLIENT_ID
        sync: false
      - key: HABU_CLIENT_SECRET
        sync: false
      - key: HABU_USE_MOCK_DATA
        value: "true"
      - key: PORT
        value: "5001"

  # React Frontend
  - type: web
    name: habu-demo-frontend-v2
    env: node
    plan: free
    buildCommand: "cd demo_app && npm install && npm run build"
    startCommand: "cd demo_app && npx serve -s build -l $PORT"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://habu-demo-api-v2.onrender.com"

  # Admin App
  - type: web
    name: habu-admin-app-v2
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn joke_admin_app.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: JOKE_MCP_SERVER_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false