# render_stable.yaml - Simplified Stable Deployment
# Phase H1.1 - Redis Only (Rollback to Working State)

databases:
  - name: habu-mcp-db
    databaseName: habu_mcp_db
    user: habu_mcp_user
    plan: free

  - name: habu-redis-cache
    plan: free
    databaseName: redis_cache

services:
  # React Frontend - Simple Build
  - type: web
    name: habu-demo-frontend
    env: node
    plan: free
    buildCommand: "cd demo_app && npm install && npm run build"
    startCommand: "cd demo_app && npx serve -s build -l $PORT"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://habu-demo-api-v2.onrender.com"

  # Admin App - Database Management
  - type: web
    name: habu-admin-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn joke_admin_app.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: JOKE_MCP_SERVER_API_KEY
        value: secure-habu-demo-key-2024
      - key: ADMIN_EMAIL
        value: admin@habu-demo.com
      - key: ADMIN_PASSWORD
        value: HabuDemo2024!