# render.yaml
# Blueprint for deploying the Habu Clean Room MCP Server and React Demo App on Render.com

databases:
  - name: habu-mcp-db
    databaseName: habu_mcp_db
    user: habu_mcp_user
    plan: free

services:
  # FastMCP 2.0 Server with Habu Integration
  - type: web
    name: habu-mcp-server
    env: python    
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: JOKE_MCP_SERVER_API_KEY 
        sync: false  # Set manually in Render dashboard
      - key: HABU_CLIENT_ID
        sync: false  # Set manually in Render dashboard
      - key: HABU_CLIENT_SECRET  
        sync: false  # Set manually in Render dashboard
      - key: HABU_USE_MOCK_DATA
        value: "true"  # Enable mock mode for demos
      - key: PORT
        value: "8000"

  # Flask API Bridge for React App
  - type: web
    name: habu-demo-api
    env: python    
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python demo_api.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db
          property: connectionString
      - key: JOKE_MCP_SERVER_API_KEY 
        sync: false  # Set manually in Render dashboard
      - key: HABU_CLIENT_ID
        sync: false  # Set manually in Render dashboard  
      - key: HABU_CLIENT_SECRET
        sync: false  # Set manually in Render dashboard
      - key: HABU_USE_MOCK_DATA
        value: "true"  # Enable mock mode for demos
      - key: PORT
        value: "5001"

  # React Demo Frontend (Static Site)
  - type: web
    name: habu-demo-frontend
    env: static
    buildCommand: "cd demo_app && npm install && npm run build"
    staticPublishPath: demo_app/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://habu-demo-api.onrender.com"

  # Flask Admin Web App (Optional)
  - type: web
    name: habu-admin-app
    env: python    
    plan: free 
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn joke_admin_app.app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: habu-mcp-db  
          property: connectionString
      - key: FLASK_SECRET_KEY 
        generateValue: true
      - key: JOKE_MCP_SERVER_API_KEY 
        sync: false  # Set manually in Render dashboard
      - key: ADMIN_EMAIL
        sync: false  # Set manually in Render dashboard
      - key: ADMIN_PASSWORD
        sync: false  # Set manually in Render dashboard

